# _config.yml

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-spaceship
  - jekyll-last-modified-at

remote_theme: "mmistakes/minimal-mistakes@4.27.0"
minimal_mistakes_skin: "default"

markdown: kramdown
mathjax: true

sass:
  style: compressed

search: true
words_per_minute: 150


title: "Lorenzo Liuzzo"
email: lorenzoliuzzo@outlook.com
description: "My personal website." 
baseurl: "" 
url: "https://lorenzoliuzzo.github.io" 

author:
  name: "Lorenzo Liuzzo"
  avatar: "assets/images/profile.jpg"
  bio: ""
  location: "Milan, Italy"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:lorenzoliuzzo@outlook.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lorenzoliuzzo"

time_zone: Europe/Rome
date_format: "%Y-%m-%d"

include:
  - _pages

collections: 
  projects: 
    output: true
    path: "_projects"
    permalink: /:collection/:path/

  notes: 
    output: true
    path: "_notes"
    permalink: /:collection/:path/


defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      show_date: true
      back_to_top: true

  - scope:
      path: "_notes"
      type: notes
    values:
      layout: single
      author_profile: false
      show_date: true
      read_time: true
      back_to_top: true
      show_taxonomy: true  
      related: true

  # - scope:
  #     path: "_projects/money-ball-ai"
  #     type: projects
  #   values:
  #     read_time: true
  #     back_to_top: true
  #     sidebar:
  #       nav: "money-ball-ai-docs"


  # - scope:
  #     path: "_projects/mc-raytracing"
  #     type: projects
  #   values:
  #     read_time: true
  #     back_to_top: true
  #     sidebar:
  #       nav: "mc-raytracing-toc"


tag_archive:
  type: liquid
  path: /tags/


footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:lorenzoliuzzo@outlook.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lorenzoliuzzo"

footer_content: "Copyright &copy; 2026 Lorenzo Liuzzo"